"""
Chisquare — AI Service

Uses Google Gemini API (google-genai SDK) for all AI/LLM tasks:
- Column role suggestion
- Cleaning operation reasoning
- Result interpretation
- Report section drafting

API key is fetched from environment (worker/.env).
All calls include confidence scoring and reasoning fields (invariant A7).
"""

from __future__ import annotations

import os
import json
from typing import Any

import structlog
from google import genai
from google.genai import types as genai_types

logger = structlog.get_logger()

# Cached client
_client: genai.Client | None = None


def _get_client() -> tuple[genai.Client, str]:
    """
    Initialize Gemini client using google-genai SDK.
    Returns (client, model_name).
    """
    global _client
    api_key = os.environ["GEMINI_API_KEY"]
    model_name = os.getenv("GEMINI_MODEL")
    if not model_name:
        raise ValueError("GEMINI_MODEL environment variable is not set")
    if _client is None:
        _client = genai.Client(api_key=api_key)
    return _client, model_name


def build_column_role_prompt(
    columns: list[dict[str, Any]],
    project_context: dict[str, Any],
    instrument_questions: list[dict[str, Any]] | None,
) -> str:
    """
    Build the column role detection prompt.

    Args:
        columns: List of {name, sample_values, dtype} dicts
        project_context: {research_questions, sampling_method, target_population, geographic_scope}
        instrument_questions: Optional list of {name, label, type} from parsed instrument
    """
    parts: list[str] = []

    # Project context section
    rq = project_context.get("research_questions") or []
    rq_text = "; ".join(
        q.get("text", str(q)) if isinstance(q, dict) else str(q) for q in rq
    ) if rq else "not specified"
    sampling = project_context.get("sampling_method") or "not specified"
    population = project_context.get("target_population") or "not specified"
    geo = project_context.get("geographic_scope") or "not specified"

    parts.append(
        "## Project Context\n"
        f"This is a {sampling} survey targeting {population}.\n"
        f"Geographic scope: {geo}\n"
        f"Research questions: {rq_text}\n"
    )

    # Instrument context section
    if instrument_questions:
        parts.append("## Survey Instrument Questions")
        parts.append("The survey form has these questions:")
        for q in instrument_questions[:200]:  # cap to avoid token overflow
            name = q.get("name", "?")
            label = q.get("label", "")
            if isinstance(label, dict):
                label = next(iter(label.values()), "")
            qtype = q.get("type", "")
            parts.append(f"- {name}: {label} (type: {qtype})")
        parts.append("")

    # Columns section
    parts.append("## Dataset Columns")
    parts.append("| column_name | sample_values | dtype |")
    parts.append("|---|---|---|")
    for col in columns:
        name = col["name"]
        samples = col.get("sample_values", [])
        sample_str = ", ".join(str(s) for s in samples[:5])
        dtype = col.get("dtype", "unknown")
        parts.append(f"| {name} | {sample_str} | {dtype} |")
    parts.append("")

    # Task instructions
    parts.append(
        "## Task\n"
        "For each column above, assign exactly ONE role from this list:\n"
        "- identifier — respondent/household ID (exclude from analysis)\n"
        "- weight — survey weight for weighted analysis\n"
        "- cluster_id — cluster identifier for survey design effects\n"
        "- stratum — stratum variable for stratified sampling\n"
        "- demographic — age, gender, location, education level, etc.\n"
        "- outcome — primary outcome variable (what the survey measures)\n"
        "- covariate — control/explanatory variable\n"
        "- skip_logic — column generated by skip logic (often mostly empty)\n"
        "- metadata — timestamps, enumerator ID, GPS, internal codes\n"
        "- open_text — free text responses\n"
        "- ignore — duplicates, internal codes, irrelevant\n"
        "\n"
        "Also detect the data_type for each column from:\n"
        "continuous, categorical, binary, ordinal, likert, date, text, identifier\n"
        "\n"
        "Return a JSON array (no wrapping object) where each element has:\n"
        "- column_name: string (exact column name from the table)\n"
        "- role: string (one of the roles above)\n"
        "- confidence: number (0.0 to 1.0)\n"
        "- reasoning: string (1-2 sentences explaining why)\n"
        "- data_type: string (one of the data types above)\n"
        "\n"
        "Important rules:\n"
        "- Be conservative with confidence — only use >0.9 when truly obvious\n"
        "- If a column matches a known survey instrument question, factor that into your reasoning\n"
        "- Weight columns are CRITICAL — if present, they enable mandatory weighted analysis\n"
        "- Look for survey design columns (weight, cluster, stratum) carefully\n"
        "- Columns with mostly empty values may be skip_logic\n"
        "- Return the array directly, not wrapped in an object\n"
    )

    return "\n".join(parts)


def generate(prompt: str) -> dict[str, Any]:
    """
    Send a prompt to Gemini and return parsed JSON response.

    Args:
        prompt: The prompt to send (must instruct model to return JSON)

    Returns:
        Parsed JSON dict from model response

    Raises:
        ValueError: If response cannot be parsed as JSON
        RuntimeError: If API call fails
    """
    client, model_name = _get_client()

    config = genai_types.GenerateContentConfig(
        temperature=0.2,
        response_mime_type="application/json",
    )

    try:
        response = client.models.generate_content(
            model=model_name,
            contents=prompt,
            config=config,
        )
        text = response.text.strip()
        result = json.loads(text)
        logger.info("gemini_response_ok", prompt_len=len(prompt))
        return result
    except json.JSONDecodeError as e:
        logger.error("gemini_json_parse_error", error=str(e))
        raise ValueError(f"Model returned non-JSON response: {e}") from e
    except Exception as e:
        logger.error("gemini_api_error", error=str(e))
        raise RuntimeError(f"Gemini API call failed: {e}") from e
